In [2]:
import numpy as np 

# 1. Create a 3x3x3 array with random values 

In [5]:
S=np.random.rand(3,3,3)
S

array([[[0.76732783, 0.19755095, 0.38571839],
        [0.98370739, 0.33617983, 0.21524812],
        [0.32162076, 0.50127579, 0.89379631]],

       [[0.64622111, 0.85481231, 0.02829863],
        [0.34037394, 0.68882766, 0.95875609],
        [0.13893559, 0.69054914, 0.71534278]],

       [[0.89005087, 0.34037897, 0.51524317],
        [0.04621529, 0.24760505, 0.30086074],
        [0.24220791, 0.54898067, 0.18776217]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
a=np.diag(1+np.arange(4), k = -1)
a


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
a=np.zeros((8,8))
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [37]:
a=np.random.rand(5,5)
print("original matrix:\n",a)
amax,amin=a.max(),a.min()
a=(a-amin)/(amax-amin)
print("Normalised matrix:\n",a)

original matrix:
 [[0.30351854 0.34154743 0.10149474 0.38378742 0.53870624]
 [0.84416882 0.14404478 0.92855363 0.90456885 0.44532981]
 [0.79746616 0.87576664 0.66003693 0.42778169 0.69841004]
 [0.94176857 0.82703297 0.95142617 0.50520321 0.16668052]
 [0.8227237  0.28956114 0.48668691 0.12681216 0.3862886 ]]
Normalised matrix:
 [[0.23769423 0.28243771 0.         0.33213583 0.51440796]
 [0.8738047  0.05006291 0.97308896 0.9448693  0.40454448]
 [0.81885596 0.9109816  0.65716147 0.38389796 0.70230995]
 [0.9886372  0.85364325 1.         0.47498946 0.07669534]
 [0.84857312 0.22127243 0.45320381 0.02978759 0.33507863]]


# 5.  How to find common values between two arrays?

In [48]:
a=np.array([[1,22,43],[56,0,3]])
b=np.array([[22,0,76],[5,4,9]])
print("a:\n",a,"\nb:\n",b,"\n\ncommon values:")
c=np.intersect1d(a,b)
print(c)

a:
 [[ 1 22 43]
 [56  0  3]] 
b:
 [[22  0 76]
 [ 5  4  9]] 

common values:
[ 0 22]


# 6.How to get the dates of yesterday, today and tomorrow?

In [49]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [59]:
a=np.array([1,33,4])
b=np.array([1,33,4])
c=np.allclose(a,b)
print(c)


True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [71]:
a=np.array([56,98,88,1,22,43,66,89,44,65])
print(a)
a[a.argmax()]=0
print("replacing max element with 0:\n",a)



[56 98 88  1 22 43 66 89 44 65]
replacing max element with 0:
 [56  0 88  1 22 43 66 89 44 65]


# 9. How to print all the values of an array?

In [4]:
np.set_printoptions(threshold=np.inf)
Z = np.arange(25)
print(Z)







[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


# 10.Subtract the mean of each row of a matrix

In [5]:
a=np.arange(2,11).reshape(3,3)
print("Original matrix:\n",a)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = a - a.mean(axis=1, keepdims=True)
print(Y)


Original matrix:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Subtract the mean of each row of the said matrix:

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [38]:
a = np.random.randint(1,10,10)
print("Given vector:", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [1 2 3 2 6 1 3 5 5 3]
Indexing vector: [0 0 0 0 0 1 2 2 4 4]
Result: [2 3 4 2 7 1 3 5 5 3]


# 12.How to get the diagonal of a dot product?

In [12]:
A=[[1,2],[3,4]]
B=[[4,5],[6,7]]
c = np.dot(A,B)
print("dot product of a and b is:\n",c)
c=np.diag(c)
print("\ndiagonal of dot product is:",c)


dot product of a and b is:
 [[16 19]
 [36 43]]

diagonal of dot product is: [16 43]


# 13.How to find the most frequent value in an array?

In [34]:
a=np.random.randint(2,15,10)
print(a)
print(np.bincount(a).argmax())


[ 8 12  4  8 11  4  6  6  8  5]
8


# 14.How to get the n largest values of an array

In [35]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 3
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[7 8 9]


# 15.How to create a record array from a regular array?

In [36]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])
print(r.b)

(2, 'dd', 2.)
['a' 'dd' 'xyz' '12']
